version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: notification_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rutok
    ports:
      - "8888:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: